### ISSUE TITLE
やりたいこと！

### ISSUE THREAD

**Issue by CreamPuff-o** [r-sylph/bd-attendance#2]
## イメージ
スプレッドシート側でフロントエンドのイメージをかためました！式とかも組み込み済み！

```
占領出欠表 - メイン : みんなのステータス登録所！
    |
    +-- 占領出欠表 - 脱隊／休隊    : 履歴、メンバーが抜けた時にサブマスが手動入力！
    +-- 占領出欠表 - 分析／可視化  : グラフ、通常さわることはないっ！
    +-- 占領出欠表 - 過去実績      : ローテート時のデータバックアップ先！
```

## スクリプト概要
こーゆーの作りたいです！

##### 1.1. Sub / 日程セル全ロード
「常に」セルを起点にして縦 101、横 5 を読み込み！

##### 2.1. Func / バックアップ + ローテート (日曜 5:00 に一回実行) 
現在の日付と R 列の日付を比較！R 列が過去になっていた場合のみ処理！

- ##### 2.1.1. バックアップ
  R 列を「占領出欠表 - 過去実績」シートの末尾列にコピーバックアップ！

- ##### 2.1.2. ローテート
  R 列の日付を一週間後の日付に変更！ S, T, U 列のデータを左にずらす！

  まず最初に過去実績シートの家名をいったんハッシュに入れとく！
  { 家名: "hoge", キャラ名: "fuga", 確認フラグ: FALSE } みたいなイメージ！

  R 列を行を for でまわして、家名を取得しつつ過去実績にデータを転記する！
  この時データ入力をしながら、A 列に「◯」をつけて確認フラグを TRUE にしていく！

  最後に、確認フラグが FALSE のままだったもの全部に対して、A 列に「×」を入力！
  ↑ 面倒だけどこれはメンバーの復隊時にバグが出るのを予防することが目的！

##### 2.2. Func /「常に」補完 (毎日 3:00-4:00 に一回実行) 
「常に」に設定があれば処理！R, S, T 列に入力がある場合に処理！U 列に「常に」の値をコピー！

**Comment by CreamPuff-o** [comment]
@r-sylph TS はじめてなので細切れでれびゅーおねがいしたいっｗ どよーに 1.1. だけつくってみるっ！

**Comment by r-sylph** [comment]
現状のイメージ

index
　バックアップ開始
　　過去の出欠情報一覧 = メインシート.過去の出欠情報を切り取る()
　　バックアップシート.スケジュール情報を追加(過去の出欠情報一覧)

メインシート
　過去の出欠情報を切り取る
　　過去の出欠情報一覧を切り取りつつ右端に新しい日程を追加
　　　新しい日程カラムに「常に」カラムの値を参照しつつ出欠情報を補完しておく
　　切り取った出欠情報を返す

バックアップシート
　スケジュール情報を追加
　　受け取った情報を新規カラムとして追加？

**Comment by CreamPuff-o** [comment]
>    +-- 占領出欠表 - 分析／可視化  : グラフ、通常さわることはないっ！

分析はシートでやらないことにした！Google に任せるとシートが非常に重くなる + レイアウトもむずい！
かわりに Deploy サーバくんにスプレッドシートのデータを取りに行かせて elasticsearch にもぐもぐさせる！
bd-toho.mydns.jp 側で basic 認証をかけて Kibana でグラフィカル表示するイメージにする！

**Comment by r-sylph** [comment]
(´・ω・｀)おほーっ　wktk

**Comment by CreamPuff-o** [comment]
きのー分見た感じいい感じにまわってそうっｗｗ いえーいっ！ｗ ヽ(•̀ω•́ )ゝ✧

**Comment by r-sylph** [comment]
やったぜ！(ง `ω´)ง 
隙を見てコードリファクタリングとかしようかな(ΦωΦ)ﾌﾌﾌ…

**Comment by CreamPuff-o** [comment]
やったぜーっｗ (੭ ˃̣̣̥ ω˂̣̣̥)੭ु⁾⁾ もいもいリファクタリングやばそーーっ(ﾟＡﾟ;)!!ｗｗ wktkーｗ ٩( 'ω' )و
